/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 3ee513d80d1b8a3fb19245e115e164c3)
interface __BaseEnv_Env {
	REPLICATE_API_TOKEN: string;
	ADMIN_PASSPHRASE: string;
	TURNSTILE_SECRET_KEY: string;
	RATE_LIMITER: DurableObjectNamespace<import("./src/server").RateLimiter>;
	ANALYTICS: DurableObjectNamespace<import("./src/server").Analytics>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "RateLimiter" | "Analytics";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REPLICATE_API_TOKEN" | "ADMIN_PASSPHRASE" | "TURNSTILE_SECRET_KEY">> {}
}
